### PR TITLE
ref: Amend span creation names for RFC 101

### PR DESCRIPTION
**Pull request by AbhiPrasad**
Discussed offline we decided to change the names of the span creator methods.

- `startActiveSpan` -> `startSpan`
- `startSpan` -> `startInactiveSpan`

lmk what you all think!

### CODE REVIEW

**Review by mydea — APPROVED** [review]
:shipit: sounds good to me!

**Comment by sentrivana** [comment]
I wasn't present during the discussion that led to this change so I don't want to approve on behalf of folks that were but wanted to say this change sounds great! Definitely makes the API more intuitive. :shipit:

**Review by Lms24 — APPROVED** [review]
Nice! I'm still not a fan of the "start" naming in the callback-based API (would have preferred something like `trace`) but this is just bike-shedding at this point and I also see the value in keeping this at least _somewhat_ consistent across SDKs.  Thanks for updating!

**Review by sl0thentr0py — APPROVED** [review]
merci

**Pull request merged**
